# Welcome to Jekyll!

# Site settings
title: Unhidea 
email: unhidea@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello there! This is the ancestor of all open-source ideas on unhidea 
baseurl: "/idea" # the subpath of your site, e.g. /blog
url: "http://unhidea.github.io" # the base hostname & protocol for your site
github_username: unhidea 

# Build settings
markdown: kramdown

# il8n
languages:
  - id: zh
    name: 中文